### ISSUE TITLE
Installing sqitch_pg on MacOS fails with: Damaged tar archive error

### ISSUE THREAD

**Issue by naveenwashere** [sqitchers/homebrew-sqitch#37]
Tried installing sqitch using homebew on mac using the following commands:

```
brew tap theory/sqitch
brew install sqitch_pg
```

Logs:

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
apache-flink                                                                                             liquibase

==> Installing sqitch_pg from theory/sqitch
==> Installing dependencies for theory/sqitch/sqitch_pg: sqitch_dependencies, sqitch, postgresql
==> Installing theory/sqitch/sqitch_pg dependency: sqitch_dependencies
==> Downloading https://fastapi.metacpan.org/v1/source/DWHEELER/App-Sqitch-0.9997/META.json
Already downloaded: /Users/naveen.kalapati/Library/Caches/Homebrew/sqitch_dependencies-0.9997.json
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest Module::Build
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest Module::Build
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest Class::XSAccessor
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest Pod::Simple
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest Type::Tiny::XS
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest Clone
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest Config::GitLike
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest DBI
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest DateTime
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest DateTime::TimeZone
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest Devel::StackTrace
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest Digest::SHA
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest Encode
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest Encode::Locale
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest File::Basename
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest File::Copy
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest File::HomeDir
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest File::Path
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest File::Temp
==> cpanm --local-lib '/usr/local/Cellar/sqitch_dependencies/0.9997' --notest Getopt::Long
Last 15 lines from /Users/naveen.kalapati/Library/Logs/Homebrew/sqitch_dependencies/20.0.9997':
tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
tar: Damaged tar archive
tar: Retrying...
tar: Error exit delayed from previous errors.
! The distribution doesn't have a proper Makefile.PL/Build.PL See /private/tmp/sqitch_dependencies-20180717-45193-xz1zqx/.brew_home/.cpanm/work/1531824786.55835/build.log for details.
Configuring Getopt-Long-2.50 ... N/A

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/theory/homebrew-sqitch/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:222:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:180:in `open_api'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:294:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:227:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:240:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:368:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:364:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:418:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'

```

May I know what's the solution to this?

Thanks in advance!

**Comment by naveenwashere** [comment]
Looks like, the issue got resolved after I performed the following:
```
brew update
brew doctor
```

The second command reported that I could have issues due to multiple versions of python that's installed in my laptop using `pyenv`.

So I tried removing all version of python and pyenv itself (as I wasn't using them much), and retried installing sqitch using brew again. This seemed to work.

Don't know if that's the real issue. But for now, the issue is resolved.
